CONFIG_BOARD_FLASH_SIZE := 2
CONFIG_BL_IOT_FW_CONN_DIAG_TLV:=0
CONFIG_BL_IOT_FW_AP:=0
CONFIG_BL_IOT_FW_AMPDU:=0
CONFIG_BL_IOT_FW_AMSDU:=0
CONFIG_BL_IOT_FW_P2P:=0
CONFIG_ENABLE_PSM_RAM:=0
CONFIG_ENABLE_VFS_ROMFS:=0
CONFIG_ADC_ENABLE_TSEN:=0
CONFIG_EASYFLASH_ENABLE:=0
CONFIG_BL602_USE_ROM_DRIVER:=1
CONFIG_FREERTOS_TICKLESS_MODE:=0

CONFIG_SYS_APP_TASK_STACK_SIZE:=4096
CONFIG_SYS_APP_TASK_PRIORITY:=15
CONFIG_SYS_VFS_ENABLE:=0
CONFIG_SYS_VFS_UART_ENABLE:=0
CONFIG_SYS_AOS_CLI_ENABLE:=0
CONFIG_SYS_AOS_LOOP_ENABLE:=1
CONFIG_SYS_BLOG_ENABLE:=0
CONFIG_SYS_DMA_ENABLE:=0
CONFIG_SYS_USER_VFS_ROMFS_ENABLE:=0

CONFIG_BT:=0
CONF_ENABLE_COREDUMP:=0
